import { Inter } from "next/font/google";
import "./globals.css";
import ConnectionProvider from "@/providers/connection";
import Chats from "@/components/chats";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en-MX">
      <body style={inter.style} className="flex h-[100dvh]">
        <ConnectionProvider>
          <Chats />
          {children}
        </ConnectionProvider>
      </body>
    </html>
  );
}
